name: Karen's Hello World Plugin
description: Hello-world project on Buildkite plugins
author: https://github.com/karensawrey
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false