#!/bin/bash

set -euo pipefail

echo "Let's see if the README is using BE or AE"

# American & British spelling dictionary
american_words=(
  "color" "center" "honor" "theater" "flavor" "aluminum" "favorite" "program"
  "labor" "partner" "traveler" "jewelry" "kilometer" "liter" "meter" "organization"
  "cancelled" "practice" "realised" "analyse" "optimisation" "analogue" "civilization"
  "manoeuvre" "grey" "offense" "defense" "judgment" "enrollment" "vacation" "ambulance"
  "skeletal" "toward" "donut" "truck" "cookies" "pants"  "crazy" "ranch"
)
british_words=(
  "colour" "centre" "honour" "theatre" "flavour" "aluminium" "favourite" "programme"
  "labour" "partner" "traveller" "jewellery" "kilometre" "litre" "metre" "organisation"
  "cancelled" "practise" "realised" "analyse" "optimisation" "analogue" "civilisation"
  "manoeuvre" "gray" "offence" "defence" "judgement" "enrolment" "holiday" "ambulance"
  "skeletal" "towards" "doughnut" "lorry" "biscuits" "trousers" "crazy" "ranch"
)

# checking what's up in the readme
function count_words() {
  local word_list="$1"

# fetching README content [dirty hack with providing the full path]
  curl -s https://raw.githubusercontent.com/karensawrey/khw-buildkite-plugin/main/README.md | \
    tr '[[:upper:]]' '[[:lower:]]' | \
    grep -Eo "[[:alpha:]]+" | \
    grep -c -w "$word_list"
}

# counging occurrences of AE and BE words
american_count=$(count_words "${american_words[@]}")
british_count=$(count_words "${british_words[@]}")

# Determine the result based on word counts
if [[ $american_count -gt $british_count ]]; then
  echo "American English"
elif [[ $british_count -gt $american_count ]]; then
  echo "British English"
else
  echo "Both or impossible to determine"
fi
